---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
  name: {{ .Values.velero.credentials.existingSecret }}
spec:
  encryptedData:
    cloud: AgBFJBOGuh+HWyvCJC0MSt3OrTMGJ221rwUiDwx+UBnCyx+pyaeX8x2Q4RVIi3yNfnaTcqZN+qHUDctxEYq+U5gmWH/td1DtS8KYW7SgwscqZIxD9S3qxy+sqSgp64pJgF8IXXQlxhyMtI+SgZaAQ8GE5mmDon73WsSFS35uaquu4KGRvQB9v47GpyWtBmPoXVya8i/r1k9xTtZIZaeqkbZpBeenY2hqNiwnfIDKV7sAr9DPyNJ0F1dqPyzG4HcsP2VkoWMB7pbct5cxGSd2kYNLzb9nm1bl96O9s/wpMXCqLzVPwtTFqnw6bvB6vHxmDyETBZOCWj+7oiUl8pFrRkq0OON0Vh91JhwGm3WFexpVF7ibxqnaMAPCU3JTTtXasIWw9qoPIweGjeNA6lpF6M0JZBfQoROQJU0Vk6cKnO+3BtL+hizcu9HvVBX77r6+9z8fwurUM/F4uwSvFn+hOxN3Y1NEYMgT5Sxa76MSuUGG5dnkSpuk3zd4q3UCODwxBJpJfJ5MdHw24M+TLy4mQdMcHN+MXKdvE8u+CXa2mxEC9Z54zSGJB1/j4t/OuD9L1kBRbTBOY06/ukuMi9Eggi9WmFP8hqB/ebe/NqGAoD0Yu5EDPdc4ZATEITdfXdpyaDNqU6i/NWyGARn2Q/3an9H0oUqzipEl+T4ntQPVLLT52PiYhG8mdyEXUtmmswHlt0vH/DNnw0JJGQnLTXETPvJB9NmBE8dja8crC7rERyMAYEtpraMWzazh+0ndK28SYhpPRxViFst7jKTds87klOuj5YWk9cTfYRYXPFIIJLbOCNbjxsPiFr8WDR/NVY4kxKCG3gs+RbHhzejoPTiok2Gdk61fzw==
  template:
    metadata:
      name: {{ .Values.velero.credentials.existingSecret }}
      namespace: {{ .Release.Namespace }}
    type: Opaque