{{- if .Values.velero.credentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.velero.credentials.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
    vault-injection: enabled
    version: "v0.0.1"
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/mutate-configmap: "true"
type: Opaque
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gJHt2YXVsdDpzZWNyZXQvZGF0YS92ZWxlcm8vYXdzI2F3c19hY2Nlc3Nfa2V5X2lkfQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSAke3ZhdWx0OnNlY3JldC9kYXRhL3ZlbGVyby9hd3MjYXdzX3NlY3JldF9hY2Nlc3Nfa2V5fQo=
{{- end }}
