velero:
  image:
    repository: docker.io/velero/velero
  labels:
    app: velero
  podLabels:
    app: velero
  resouces:
    requests:
      cpu: 200m
  initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins