apiVersion: v2
appVersion: 1.9.1
kubeVersion: ">=1.16.0-0"
description: A Helm chart for velero
name: velero
version: 2.31.8
home: https://github.com/vmware-tanzu/velero
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
sources:
- https://github.com/vmware-tanzu/velero
maintainers:
  - name: jenting
    email: hsiaoairplane@gmail.com
  - name: sseago
    email: sseago@redhat.com
  - name: reasonerjt
    email: jiangd@vmware.com
  - name: ywk253100
    email: yinw@vmware.com
dependencies:
- name: velero
  repository: https://vmware-tanzu.github.io/helm-charts
  version: 2.31.6
  alias: velero
