defaultNamespace: velero

helm:
  releaseName: velero
  valuesFiles:
  - values/velero-values.yaml

targetCustomizations:
- name: k8s-us-east
  helm:
    valuesFiles:
    - values/k8s-us-east-values.yaml
  clusterSelector:
    matchLabels:
      name: k8s-us-east